### PR TITLE
Feature: Upload throttling processing

### PR DESCRIPTION
**Pull request by andrewshkovskii**

### CODE REVIEW

**Comment by andrewshkovskii** [comment]
[Обновить migro для upload throttles](https://trello.com/c/C5exOSxc/474-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-migro-%D0%B4%D0%BB%D1%8F-upload-throttles)

**Comment by andrewshkovskii** [comment]
@sharov Можно по коммитам посмотреть

**Comment by dmitry-mukhin** [comment]
@andrewshkovskii do upload servers indicate what time a client should wait? if they do, we could try to use that as timeout.

**Comment by andrewshkovskii** [comment]
@dmitry-mukhin Please, see #7

**Comment by dmitry-mukhin** [comment]
👍
also, I'm blind

**Pull request merged**
